# Generated by Django 3.2 on 2022-10-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='instance_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
