# Generated by Django 3.2 on 2022-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_changelog_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(max_length=5000),
        ),
    ]
